language: en

pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngarm: 4
- name: DIETClassifier
  entity_recognition: false
  epochs: 100
- name: RegexEntityExtractor
  use_lookup_tables: true

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
assistant_id: 20230430-233919-worn-swamp
